spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: bestuser
    password: bestuser

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  thymeleaf:
    enabled: true
    encoding: UTF-8
    cache: false
    check-template: true
    check-template-location: true
    mode: HTML
    template-resolver-order: 0
#    prefix: classpath:/templates/view/